name: 'codemention: populate cache'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  populate_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./populate-cache
