name: 'codemention: populate cache'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  populate_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./populate-cache
